version: '3.8'
services:
    laravel:
        image: test
        build:
            context: .
            dockerfile: Dockerfile      
        ports:
            - 80:80
        volumes:
            - './src:/var/www'
            - './src/public:/var/www/html'
