version: '3'
services:
    laravel:
        image: bitnami/laravel
        container_name: laravel
        ports:
            - '${APP_PORT:-80}:8000'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        volumes:
            - './src:/app'
        working_dir: /app
        entrypoint:
            [
                "php",
                "artisan",
                "serve",
                "--host=0.0.0.0",
                "--port=8000"
            ]
    db: 
        image: mariadb
        container_name: db
        environment:
            - MYSQL_DATABASE=insight
            - MYSQL_ROOT_PASSWORD=root